### ISSUE TITLE
Round-end-message not correct.

### ISSUE THREAD

**Issue by TilmanK** [opcode81/Sketchers#38]
» Penislukenöffner is drawing!
Tilman: nutte
Katapulze: omma
Tilman: crack
Katapulze: mudda
Honkisponk: Anmut
Katapulze: scheisse
Tilman: ommma
Harry Haller: blut
Harry Haller: farbe
Honkisponk: Japan
Messer: Lippe
Harry Haller: mund
Harry Haller: bart
Tilman: fresse
Messer: Suppe
Harry Haller: suppe
Honkisponk: Soße
Katapulze: atomkrieg
Tilman: lippe
Kleola: suppe
Honkisponk: Chips
Harry Haller: topf
opcode: suppe
Honkisponk: Tortilla
» simon guessed the word after 43 s.
» Messer guessed the word after 43 s.
Kleola: nacho
Dea: nacho
Tilman: nacho
opcode: nacho
Honkisponk: Nachos
» Harry Haller guessed the word after 47 s.
» Kleola guessed the word after 47 s.
Honkisponk: Nacho
Tilman: tacos
Tilman: chips
» Harry Haller left.
» Katapulze guessed the word after 60 s.
opcode: tacco
opcode: nacho
Tilman: tacos
opcode: tacos
» opcode guessed the word after 72 s.
Honkisponk: Nacho
» Dea guessed the word after 75 s.
» Tilman guessed the word after 82 s.
» All players guessed correctly. The word was Salsa.

**Comment by TilmanK** [comment]
Honkisponk never guessed the word correct.

**Comment by opcode81** [comment]
This has been fixed (cause: player who had guessed the word left the game); also fixed the problem of re-checking the 'end of round condition' whenever a player leaves the game.
