### ISSUE TITLE
Disconnect causes player hickput

### ISSUE THREAD

**Issue by TilmanK** [opcode81/Sketchers#42]
Katapulze got into => Player 25

» Katapulze guessed the word after 33 s.
» Honkisponk guessed the word after 33 s.
» simon guessed the word after 34 s.
Penislukenöffner: Seil
Tilman: seil
» Dea guessed the word after 36 s.
» Penislukenöffner guessed the word after 39 s.
» Tilman guessed the word after 43 s.
Penislukenöffner: Flos
Penislukenöffner: Flo
Penislukenöffner: Floss
» Katapulze left.
Honkisponk: Floß?
» Player passed. The word was Floß.
» Honkisponk is drawing!
Tilman: cracknutte
Harry Haller: surfer
Harry Haller: rakete
simon: rakete
Tilman: rakete
Tilman: tampon
Harry Haller: raketen
opcode: rakete
Harry Haller: antrieb
simon: RAKETEN
Player25: flops
» Harry Haller guessed the word after 46 s.
Tilman: zämpfchen
Tilman: penis
Tilman: rakete
Player25: pilot
Player25: braun
» opcode guessed the word after 83 s.
» Kleola guessed the word after 86 s.
Player25: ocket
» Tilman guessed the word after 93 s.
Penislukenöffner: racket
Dea: rackete
» Player25 guessed the word after 96 s.
simon: racket
» Dea guessed the word after 102 s.
» simon guessed the word after 106 s.
simon: :/
» Player25 left.

**Comment by opcode81** [comment]
This has been fixed.
